name: Deno CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno cache ./server/main.ts

      - name: Run tests
        run: deno test --allow-net
